version: '3.4'

services:
  todo-app-api:
    image: todo-app-api
    build:
      # El contexto es la raíz (donde está el .sln y el docker-compose.yml)
      context: . 
      # La ruta al Dockerfile dentro de ese contexto
      dockerfile: TODO.WebApi/Dockerfile 
    ports:
      - "8980:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

